### ISSUE TITLE
4. 색칠하기 잘못된 액션 알림

### ISSUE THREAD

**Issue by lhjgo** [gasbank/black#26]
- 작업 목표일: 12월 12일
- [x] 일반 스테이지에서는 페널티 없고 알려주는 용도만 (전체 화면 빨간색 번쩍)
- [ ] 관문 스테이지에서는 시간 페널티

**Comment by gasbank** [comment]
매우 작은 칸 등 페널티 없이도 스트레스 받는 경우가 뒤로 갈 수록 급증하므로, 관문 스테이지라도 시간 페널티는 없는 것으로 하시죠.

**Comment by lhjgo** [comment]
좋습니다 그러면 현재 상태에서 종료하도록 하죠
