### ISSUE TITLE
잘못된 색칠 알람 색 변경

### ISSUE THREAD

**Issue by lhjgo** [gasbank/black#36]
- [x] 기존 붉은 색은 너무 거슬리므로 녹색으로 변경, 채도도 조금 낮게
- [x] 가능하다면 이미 채운 곳은 콤보만 깨지게 하고 가이드 안되도록 해보자

**Comment by gasbank** [comment]
빈 칸에 틀린 팔레트로 칠하려고 했을 때만 잘못된 색칠 알람 되도록 제가 수정했습니다.
