### ISSUE TITLE
Maintenance for BE part

### ISSUE THREAD

**Issue by lacti** [gasbank/black#62]
[BE](https://github.com/gasbank/black/tree/master/be) 파트가 너무 노후화되었습니다. 다행히 아직 기능은 잘 동작하는 것으로 보이나, 의존성 문제로 인해 계속 기계적인 bump PR이 발생하는 상황입니다.

@gasbank 
따라서 다음과 같이 제안 드립니다. 두 가지 방법 중, 더 선호하는 방향이 있다면 말씀 부탁 드립니다.

- [x] BE 기능을 더 이상 사용하지 않으므로 프로젝트에서 제거.
- ~~[ ] BE 기능의 의존성을 최신화.~~

사용하지 않는다면 제거하는 편이 낫습니다. 만약 앞으로 사용할 계획이 있다면, 현재 기준으로 의존성을 최신화하고 관련 문서를 보완해두겠습니다. 의견 부탁 드립니다.

**Comment by gasbank** [comment]
@lacti 제거 해 주시길 부탁드립니다. 게임 부분이 좀 돌아가게 되면 다시 부탁드리겠습니다.

**Comment by lacti** [comment]
#63 
Done.
